In [1]:
import tensorflow as tf
print(tf.__version__)

2.10.0


## 🛠 Exercises

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.
7. Find the min and max values of the tensor you created in 6.
8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.
9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.

### 1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.

In [2]:
vector = tf.constant([4, 10])
print(type(vector))
vector

<class 'tensorflow.python.framework.ops.EagerTensor'>


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 4, 10])>

In [3]:
scalar = tf.constant(4)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [4]:
matrix = tf.constant([[10, 20],
                      [4,7],
                      [5,8]])
print("matrix Dimension: ",matrix.ndim)
print("matrix Shape: ",matrix.shape)
matrix

matrix Dimension:  2
matrix Shape:  (3, 2)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 20],
       [ 4,  7],
       [ 5,  8]])>

In [5]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
print("Tensor Dimension: ",tensor.ndim)
print("Tensor Shape: ",tensor.shape)

tensor

Tensor Dimension:  3
Tensor Shape:  (3, 2, 3)


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

### 2. Find the shape, rank and size of the tensors you created in 1.

In [6]:
print("vector Shape: ",vector.shape)
print("vector Dimension: ",vector.ndim)
print("vector Size: ",tf.size(vector))

print("-"*120)
print("scalar Shape: ",scalar.shape)
print("scalar Dimension: ",scalar.ndim)
print("scalar Size: ",tf.size(scalar))

print("-"*120)


print("matrix Shape: ",matrix.shape)
print("matrix Dimension: ",matrix.ndim)
print("matrix Size: ",tf.size(matrix))
print("-"*120)

print("tensor Shape: ",tensor.shape)
print("tensor Dimension: ",tensor.ndim)
print("tensor Size: ",tf.size(tensor))

vector Shape:  (2,)
vector Dimension:  1
vector Size:  tf.Tensor(2, shape=(), dtype=int32)
------------------------------------------------------------------------------------------------------------------------
scalar Shape:  ()
scalar Dimension:  0
scalar Size:  tf.Tensor(1, shape=(), dtype=int32)
------------------------------------------------------------------------------------------------------------------------
matrix Shape:  (3, 2)
matrix Dimension:  2
matrix Size:  tf.Tensor(6, shape=(), dtype=int32)
------------------------------------------------------------------------------------------------------------------------
tensor Shape:  (3, 2, 3)
tensor Dimension:  3
tensor Size:  tf.Tensor(18, shape=(), dtype=int32)


### 3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.


In [7]:
random1 = tf.random.Generator.from_seed(42)
random1 = random1.uniform(shape=(5,300))

In [8]:
tf.math.reduce_max(random1)

<tf.Tensor: shape=(), dtype=float32, numpy=0.99872065>

In [9]:
tf.math.reduce_min(random1)

<tf.Tensor: shape=(), dtype=float32, numpy=0.0003619194>

In [10]:
random2 = tf.random.Generator.from_seed(45)
random2 = random2.uniform(shape=(5,300))

### 4. Multiply the two tensors you created in 3 using matrix multiplication.


In [11]:
# Method - 1
prod = tf.matmul(random1, random2, transpose_a=True)

In [12]:
prod

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[1.7799168 , 1.7776245 , 1.9646808 , ..., 2.219033  , 1.3694499 ,
        1.1903923 ],
       [1.2603954 , 1.7817576 , 1.9220937 , ..., 1.7505955 , 1.4332385 ,
        0.9630243 ],
       [0.91638625, 0.83087593, 1.255487  , ..., 0.9712593 , 0.64660096,
        0.8157369 ],
       ...,
       [0.93565613, 0.7607054 , 0.7439692 , ..., 0.9534668 , 0.46746138,
        0.71517247],
       [1.695093  , 1.5236593 , 1.8659173 , ..., 2.0326788 , 1.2023041 ,
        1.1116064 ],
       [1.3886744 , 1.178704  , 1.3936479 , ..., 1.6372824 , 0.8279296 ,
        1.0887885 ]], dtype=float32)>

In [13]:
# Method -2
random1_reshaped = tf.reshape(random1, shape=(random1.shape[1], random1.shape[0]))
random2 @ random1_reshaped

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[76.614876, 73.67309 , 74.501434, 76.56241 , 76.689545],
       [68.79084 , 69.50687 , 71.91168 , 71.550735, 74.64726 ],
       [74.10363 , 72.27151 , 77.25077 , 73.50989 , 73.69415 ],
       [73.328896, 73.3215  , 73.80848 , 74.68616 , 76.37677 ],
       [72.147125, 72.533295, 72.413376, 73.97733 , 74.75777 ]],
      dtype=float32)>

### 5. Multiply the two tensors you created in 3 using dot product.


In [17]:
dotProduct = tf.tensordot(random1_reshaped, random2, axes=1)
dotProduct

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[1.2134517 , 1.5932388 , 1.7245263 , ..., 1.8316574 , 1.2614535 ,
        0.9618634 ],
       [1.460104  , 1.7780542 , 2.2010393 , ..., 2.1343417 , 1.5242041 ,
        1.016547  ],
       [1.7459371 , 1.7224977 , 2.129097  , ..., 2.1066253 , 1.292932  ,
        1.4329472 ],
       ...,
       [0.6234001 , 1.3293637 , 1.7475382 , ..., 1.4068817 , 1.2840532 ,
        0.49095592],
       [1.534241  , 2.1432726 , 2.3019857 , ..., 2.2218306 , 1.7763214 ,
        1.0321026 ],
       [0.8402395 , 0.9160868 , 1.6085006 , ..., 1.6036739 , 0.95527184,
        0.5869971 ]], dtype=float32)>

### 6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.


In [19]:
random3 = tf.random.Generator.from_seed(42)
random3 = random3.uniform(shape=(224,224,3))
random3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.7493447 , 0.73561966, 0.45230794],
        [0.49039817, 0.1889317 , 0.52027524],
        [0.8736881 , 0.46921718, 0.63932586],
        ...,
        [0.8035464 , 0.8265822 , 0.84540355],
        [0.16108847, 0.48667014, 0.6170937 ],
        [0.22355545, 0.93454087, 0.5319209 ]],

       [[0.7508148 , 0.46019256, 0.14229465],
        [0.10500956, 0.72874916, 0.89662087],
        [0.85220826, 0.76973283, 0.11408448],
        ...,
        [0.38387823, 0.72712064, 0.7561674 ],
        [0.70352066, 0.22680473, 0.24423313],
        [0.39240444, 0.32533252, 0.39407527]],

       [[0.74291146, 0.54543686, 0.32094967],
        [0.6671035 , 0.8900143 , 0.64271927],
        [0.5317905 , 0.21345353, 0.71189904],
        ...,
        [0.53968227, 0.7233304 , 0.7900686 ],
        [0.99334645, 0.857829  , 0.67977047],
        [0.8087704 , 0.06597769, 0.62171316]],

       ...,

       [[0.84861326, 0.6271888 , 0.7023717 ],
        [0.46

### 7. Find the min and max values of the tensor you created in 6.


In [20]:
lowest = tf.math.reduce_min(random3)
highest = tf.math.reduce_max(random3)

lowest, highest

(<tf.Tensor: shape=(), dtype=float32, numpy=4.053116e-06>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.99998736>)

### 8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.


In [21]:
random4 = tf.random.Generator.from_seed(50)
random4 = random4.uniform(shape=(1,224,224,3))
random4.shape

TensorShape([1, 224, 224, 3])

In [22]:
random4_squeezed = tf.squeeze(random4)
random4_squeezed.shape

TensorShape([224, 224, 3])

### 9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.


In [25]:
lst = [4,5,8,7,4,6,4,1,2,4]
t5 = tf.constant(lst)

tf.math.argmax(t5)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

### 10. One-hot encode the tensor you created in 9.

In [30]:
tf.one_hot(t5, depth=len(set(lst))-1)

<tf.Tensor: shape=(10, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.]], dtype=float32)>